name: Style

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: configure
      run: cmake -Htest -Bbuild

    - name: build
      run: cmake --build build

    - name: test
      run: CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --target test
