name: MacOS

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: configure
      run: cmake -Htest -Bbuild

    - name: check style
      run: cmake --build build --target check-format
