name: Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: configure
      run: cmake -Htest -Bbuild

    - name: build
      run: cmake --build build

    - name: test
      run: ./build/BitViewTests
